# Kernel Build Options
CONFIG_KERNEL_DEBUG_INFO=n
CONFIG_TARGET_ROOTFS_INITRAMFS=n

# Themes
CONFIG_PACKAGE_luci-theme-argon=y

# Protocols
CONFIG_PACKAGE_luci-proto-ipv6=y
CONFIG_PACKAGE_luci-proto-ppp=y
CONFIG_PACKAGE_luci-proto-wireguard=y

# Applications
CONFIG_PACKAGE_ca-bundle=y
CONFIG_PACKAGE_ca-certificates=n
CONFIG_PACKAGE_coremark=n
CONFIG_PACKAGE_ddns-scripts=n
CONFIG_PACKAGE_ddns-scripts-cloudflare=n
CONFIG_PACKAGE_ddns-scripts-dnspod-com=n
CONFIG_PACKAGE_ddns-scripts-dnspod=n
CONFIG_PACKAGE_ddns-scripts-services=n
CONFIG_PACKAGE_ddns-scripts_aliyun=n
CONFIG_PACKAGE_ddns-scripts_dnspod=n
CONFIG_PACKAGE_default-settings=y
CONFIG_PACKAGE_default-settings-chn=y
CONFIG_PACKAGE_dnsmasq=n
CONFIG_PACKAGE_dnsmasq-full=y
CONFIG_PACKAGE_openssh-sftp-server=y
