name: "Flippy Wrapper"
description: "A wrapper to fix path issues in Reusable Workflows for ophub/flippy-openwrt-actions"

runs:
  using: composite
  steps:
    - name: "Checkout"
      uses: actions/checkout@main
      with:
        repository: ophub/flippy-openwrt-actions
        ref: main
        path: .actions/flippy_packit

    - name: "Flippy"
      shell: bash
      env:
        FLIPPY_SCRIPT: .actions/flippy_packit/openwrt_flippy.sh
      run: |
        trap 'rm -rf .actions' EXIT

        sudo rm -rf /opt
        sudo mkdir -p /builder/opt
        sudo ln -sfn /builder/opt /opt
        sudo chown -R "$(id -u):$(id -g)" /builder/opt
        sudo chmod -R u+rwx /builder/opt

        if [[ -f "${FLIPPY_SCRIPT}" ]]; then
          chmod +x "${FLIPPY_SCRIPT}"
          "${FLIPPY_SCRIPT}"
        fi

        sudo chown -R "$(id -u):$(id -g)" /builder/opt
