# Build Firmware
CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_d-team_newifi-d2=y

# Kernel Build Options
CONFIG_KERNEL_CC_OPTIMIZE_FOR_SIZE=y

# Applications
CONFIG_PACKAGE_bash=n
CONFIG_PACKAGE_luci-app-ddns-go=n
CONFIG_PACKAGE_luci-app-tailscale-community=n
