# Build Firmware
CONFIG_TARGET_armsr=y
CONFIG_TARGET_armsr_armv8=y
CONFIG_TARGET_armsr_armv8_DEVICE_generic=y

# Kernel Build Options
CONFIG_KERNEL_CC_OPTIMIZE_FOR_SIZE=n

# Applications
CONFIG_PACKAGE_automount=y
CONFIG_PACKAGE_luci-app-amlogic=y
CONFIG_PACKAGE_xz-utils=y
CONFIG_PACKAGE_zram-swap=n
